% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Nov-2024 14:39:05
%  MATLAB version: 24.2.0.2790852 (R2024b) Update 2
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

A = 0.01;

Fs = 44100;

T = 2;

a = [1 -7.93266348200987 27.531218981269223 -54.601320717697632 67.681541561072308 ...
     -53.694116817558886 26.623956666404617 -7.5437950494798214 0.93517885800007472 ...
     ];

amplified_signal = saveVarsMat.amplified_signal; % <1x44101 double> too many elements

b = [2.6150362212859984E-8 0 -1.0460144885143994E-7 0 1.569021732771599E-7 ...
     0 -1.0460144885143994E-7 0 2.6150362212859984E-8];

beat_interval = 0.8;

f = 100;

f1 = 50;

f2 = 100;

filtered_signal = saveVarsMat.filtered_signal; % <1x88200 double> too many elements

gain = 100;

heart_rate = 75;

heart_sound = saveVarsMat.heart_sound; % <1x88200 double> too many elements

high_cutoff = 200;

i = 2;

input_signal = saveVarsMat.input_signal; % <1x44101 double> too many elements

low_cutoff = 20;

noise_level = 0.1;

noisy_signal = saveVarsMat.noisy_signal; % <1x88200 double> too many elements

s1 = saveVarsMat.s1; % <1x88200 double> too many elements

s2 = saveVarsMat.s2; % <1x88200 double> too many elements

snr_amplified = 0.98736360793090472;

snr_filtered = NaN;

snr_original = 0.98736360793090328;

t = saveVarsMat.t; % <1x44101 double> too many elements

t1 = 1.6;

t2 = 1.9000000000000001;

clear saveVarsMat;
